spring.application.name=TrackerGym

# Conexión a Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}



# JPA / Hibernate
# Usamos 'update' para que Hibernate cree/actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto para MySQL 8+
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Evitar errores de Lazy Initialization en las vistas
spring.jpa.open-in-view=true